name: deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: kokko.ch
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: 'dist/'
          target: '~/public_html/shared/kokko.ch'
          rm: true
          strip_components: 1
